- add at least 3 records into each table

INSERT INTO Customers (ID,Firstname,Lastname,CardNumber) VALUES (1,'James','Weight','9000123400001234');
INSERT INTO Customers (ID,Firstname,Lastname,CardNumber) VALUES (2,'Yes','No','1000123400001234');
INSERT INTO Customers (ID,Firstname,Lastname,CardNumber) VALUES (3,'Great','Good','7200123400001234');

INSERT INTO Products (ID,Name,Price) VALUES (1,'Widget',1.25);
INSERT INTO Products (ID,Name,Price) VALUES (2,'Apparatus',2.5);
INSERT INTO Products (ID,Name,Price) VALUES (3,'Gizmo',3);

INSERT INTO Orders (ID,ProductID,CustomerID) VALUES (1,1,1);
INSERT INTO Orders (ID,ProductID,CustomerID) VALUES (2,2,2);
INSERT INTO Orders (ID,ProductID,CustomerID) VALUES (3,3,3);

- add product iPhone at $200

INSERT INTO Products (ID,Name,Price) VALUES (4,'iPhone',200);

- add customer Tina Smith

INSERT INTO Customers (ID,Firstname,Lastname,CardNumber) VALUES (4,'Tina','Smith',NULL);

- create order for Tina Smith bought on iPhone

INSERT INTO Orders (ID,ProductID,CustomerID) VALUES (4,4,4);

- report all orders by Tina Smith

CREATE VIEW Tina_Smith_Orders AS SELECT Firstname,Lastname,Name FROM Orders WHERE Firstname='Tina' AND Lastname='Smith';

- report all revenue generated by sales of iPhone

CREATE VIEW Revenue_iPhone AS SELECT SUM() FROM Products WHERE Price>0 AND Price IS NOT NULL;

- increase the price of iPhone to $250

UPDATE Products (Price) VALUES (250) WHERE ProductID='iPhone'; 
